# 1_Tensorflow Basics

Basic and essential tensor operations using Tensorflow

In [1]:
# Optional to surpress warning
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import tensorflow as tf

# Set physical device to GPU
physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)

## Tensor Initialization

In [2]:
# Scalar integer
x = tf.constant(4)
print('printed: ',x)
x

printed:  tf.Tensor(4, shape=(), dtype=int32)


<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [3]:
# Scalar Float 
x = tf.constant(4.)
print('printed: ',x)
x

printed:  tf.Tensor(4.0, shape=(), dtype=float32)


<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [4]:
# Custom shape & dtype Tensor
x = tf.constant(4, shape=(1,1), dtype=tf.float32)
print('printed: ',x)
x

printed:  tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [5]:
# Multidimensional Tensor
x = tf.constant([[1,2,3],[4,5,6]])
print('printed: ',x)
x

printed:  tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [6]:
# Tensor of Ones
x = tf.ones((3,3))
print('printed: ',x)
x

printed:  tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [7]:
# Tensor of zeros
x = tf.zeros((2,3))
print('printed: ',x)
x

printed:  tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [8]:
# Identity matrix (eye)
x = tf.eye(3)
print('printed: ',x)
x

printed:  tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [9]:
# Normal Distribution
x = tf.random.normal((3,3), mean=0, stddev=1)
print('printed: ',x)
x

printed:  tf.Tensor(
[[-0.06908641  0.02188444 -0.45440912]
 [ 0.33479214 -0.705297    1.2631892 ]
 [-0.5975696  -0.85097927  2.7074401 ]], shape=(3, 3), dtype=float32)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.06908641,  0.02188444, -0.45440912],
       [ 0.33479214, -0.705297  ,  1.2631892 ],
       [-0.5975696 , -0.85097927,  2.7074401 ]], dtype=float32)>

In [10]:
# Uniform Distribution
x = tf.random.uniform((1,3), minval=0, maxval=1)
print('printed: ',x)
x

printed:  tf.Tensor([[0.8677671  0.3265133  0.69214237]], shape=(1, 3), dtype=float32)


<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.8677671 , 0.3265133 , 0.69214237]], dtype=float32)>

In [11]:
# Range function
x = tf.range(9)
print('printed: ',x)
x

printed:  tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>

In [12]:
# Range function
x = tf.range(start=1, limit=10, delta=2)
print('printed: ',x)
x

printed:  tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

## Casting Datatypes

In [13]:
# Casting float
x = tf.cast(x, dtype=tf.float64)
print('printed: ',x)
x

printed:  tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 3., 5., 7., 9.])>

> **Casting:** <br>
tf.float (16,32,64), tf.int (8,16,32,64), tf.bool

## Mathematical Operations

### Element Wise Operations

In [14]:
# Example tensor
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

In [15]:
# Additional
z = tf.add(x, y)
# Or
z = x + y
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10])>

In [16]:
# Substract
z = tf.subtract(x, y)
# Or
z = x - y
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4])>

In [17]:
# Division
z = tf.divide(x, y)
# Or
z = x / y
z

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [18]:
# Multiplication
z = tf.multiply(x, y)
# Or
z = x * y
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21])>

In [19]:
# Dot Product
z = tf.tensordot(x, y, axes=1)
# Or
tf.reduce_sum(x*y, axis=0)
z

<tf.Tensor: shape=(), dtype=int32, numpy=46>

In [20]:
# Exponentiation
z = x ** 5
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([  1,  32, 243])>

In [21]:
# Matrix Multiplication
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))

z = tf.matmul(x, y)
# Or
z = x @ y
z

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 0.28353363,  0.31343585, -0.591114  ,  1.1212991 ],
       [-0.5298776 ,  2.3607621 ,  0.58345795, -2.9113858 ]],
      dtype=float32)>

## Indexing

In [22]:
x = tf.constant([0,1,1,2,3,1,2,3])
print(x)

# Get All
print(x[:])
# Exclude the first item
print(x[1:])
# Exclude first and item after index 3
print(x[1:3])
# All values but skip some element
print(x[::2])
# Reverse order
print(x[::-1])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [23]:
# Indices
indices = tf.constant([0,3])
x_ind = tf.gather(x, indices)
x_ind

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 2])>

In [24]:
# Ndim indices
x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
# Get 1st row all element
print(x[0]) # or x[0,:]
# Pick first 2 rows
print(x[0:2,:])

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


## Reshaping Tensor

In [25]:
x = tf.range(9)

print(x)
# Reshape
x = tf.reshape(x, (3,3))
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [26]:
# Transpose
x = tf.transpose(x, perm=[1,0])
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])>